export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAILURE = "GET_USERS_FAILURE";

export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
export const ADD_USER_FAILURE = "ADD_USER_FAILURE";

export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAILURE = "DELETE_USER_FAILURE";

export const GET_EVENTS_SUCCESS = "GET_EVENTS_SUCCESS";
export const GET_EVENTS_FAILURE = "GET_EVENTS_FAILURE";

export const CREATE_EVENT_SUCCESS = "CREATE_EVENT_SUCCESS";
export const CREATE_EVENT_FAILURE = "CREATE_EVENT_FAILURE";

export const DELETE_EVENT_SUCCESS = "DELETE_EVENT_SUCCESS";
export const DELETE_EVENT_FAILURE = "DELETE_EVENT_FAILURE";

export const CREATE_POLL_SUCCESS = "CREATE_POLL_SUCCESS";
export const CREATE_POLL_FAILURE = "CREATE_POLL_FAILURE";

export const NOTIFY_USERS_SUCCESS = "NOTIFY_USERS_SUCCESS";
export const NOTIFY_USERS_FAILURE = "NOTIFY_USERS_FAILURE";

export const CAST_VOTE_SUCCESS = "CAST_VOTE_SUCCESS";
export const CAST_VOTE_FAILURE = "CAST_VOTE_FAILURE";

export const GET_POLL_SUCCESS = "GET_POLL_SUCCESS";
export const GET_POLL_FAILURE = "GET_POLL_FAILURE";

export const SUBMIT_ATTENDANCE_SUCCESS = "SUBMIT_ATTENDANCE_SUCCESS";
export const SUBMIT_ATTENDANCE_FAILURE = "SUBMIT_ATTENDANCE_FAILURE";

export const SET_USER_ATTENDANCE_SUCCESS = "SET_USER_ATTENDANCE_SUCCESS";
export const SET_USER_ATTENDANCE_FAILURE = "SET_USER_ATTENDANCE_FAILURE";
